### ISSUE TITLE
help with `backup:clean`

### ISSUE THREAD

**Issue by foremtehan** [masbug/flysystem-google-drive-ext#26]
I know it's nothing to do with this package, But wondering why the command `backup:clean` from https://github.com/spatie/laravel-backup doesnt clean up the old backups ? Previously i was using https://github.com/nao-pon/flysystem-google-drive as google adapter but since it shows the files as raw string so i tought it was the issue then i installed this package, but still no luck the old file still remain in the storage 2021-07-03-17-14-36.zip

```
Starting cleanup...
Cleaning backups of  on disk local...
Used storage after cleanup: 0 B.
Cleaning backups of  on disk google...
Used storage after cleanup: 3.73 GB.
Cleanup completed!
```

**Comment by erikn69** [comment]
> nothing to do with this package

The question should not be here, but I will answer it
It´s working with spatie/laravel-backup because i'm using it, here is the test
![image](https://user-images.githubusercontent.com/4933954/125347656-cc3de880-e320-11eb-89f0-fd56ec0a5d50.png)
![image](https://user-images.githubusercontent.com/4933954/125347754-ec6da780-e320-11eb-886f-001249dacca3.png)
So, maybe your config is failing, take a look to your `cleanup` strategy
